// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4d567tTwF5EDt0NLYyhtQx7Gligpe3HY',
    appId: '1:207615161702:web:997cf7fd461666613bc4a7',
    messagingSenderId: '207615161702',
    projectId: 'mobilebuild-2df17',
    authDomain: 'mobilebuild-2df17.firebaseapp.com',
    storageBucket: 'mobilebuild-2df17.firebasestorage.app',
    measurementId: 'G-XZSZERGWYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByvxTBIpXL9uE__aH7ujuO8xHIn0m3ihY',
    appId: '1:207615161702:android:0dfb593e8330913f3bc4a7',
    messagingSenderId: '207615161702',
    projectId: 'mobilebuild-2df17',
    storageBucket: 'mobilebuild-2df17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW6BRwnzaciUQcas-EUAuBO9h6IKTNCBE',
    appId: '1:207615161702:ios:824667290e59571e3bc4a7',
    messagingSenderId: '207615161702',
    projectId: 'mobilebuild-2df17',
    storageBucket: 'mobilebuild-2df17.firebasestorage.app',
    iosBundleId: 'com.example.mobilebuild',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW6BRwnzaciUQcas-EUAuBO9h6IKTNCBE',
    appId: '1:207615161702:ios:824667290e59571e3bc4a7',
    messagingSenderId: '207615161702',
    projectId: 'mobilebuild-2df17',
    storageBucket: 'mobilebuild-2df17.firebasestorage.app',
    iosBundleId: 'com.example.mobilebuild',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4d567tTwF5EDt0NLYyhtQx7Gligpe3HY',
    appId: '1:207615161702:web:6f023c893fddffb83bc4a7',
    messagingSenderId: '207615161702',
    projectId: 'mobilebuild-2df17',
    authDomain: 'mobilebuild-2df17.firebaseapp.com',
    storageBucket: 'mobilebuild-2df17.firebasestorage.app',
    measurementId: 'G-FPT36067KW',
  );
}
